//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class MethodStep
    {
        public long ID { get; set; }
        public long MethodID { get; set; }
        public Nullable<long> StepType { get; set; }
        public Nullable<long> StepIndex { get; set; }
        public string Description { get; set; }
    }
}
