//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTestLocal.mwmWebServiceTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mwmWebServiceTest.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServiceTestLocal.mwmWebServiceTest.HelloWorldResponse HelloWorld(WebServiceTestLocal.mwmWebServiceTest.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceTestLocal.mwmWebServiceTest.HelloWorldResponse> HelloWorldAsync(WebServiceTestLocal.mwmWebServiceTest.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStr", ReplyAction="*")]
        WebServiceTestLocal.mwmWebServiceTest.GetStrResponse GetStr(WebServiceTestLocal.mwmWebServiceTest.GetStrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStr", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceTestLocal.mwmWebServiceTest.GetStrResponse> GetStrAsync(WebServiceTestLocal.mwmWebServiceTest.GetStrRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTestLocal.mwmWebServiceTest.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServiceTestLocal.mwmWebServiceTest.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTestLocal.mwmWebServiceTest.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServiceTestLocal.mwmWebServiceTest.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStr", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTestLocal.mwmWebServiceTest.GetStrRequestBody Body;
        
        public GetStrRequest() {
        }
        
        public GetStrRequest(WebServiceTestLocal.mwmWebServiceTest.GetStrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetStrRequestBody() {
        }
        
        public GetStrRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStrResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTestLocal.mwmWebServiceTest.GetStrResponseBody Body;
        
        public GetStrResponse() {
        }
        
        public GetStrResponse(WebServiceTestLocal.mwmWebServiceTest.GetStrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStrResult;
        
        public GetStrResponseBody() {
        }
        
        public GetStrResponseBody(string GetStrResult) {
            this.GetStrResult = GetStrResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebServiceTestLocal.mwmWebServiceTest.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebServiceTestLocal.mwmWebServiceTest.WebService1Soap>, WebServiceTestLocal.mwmWebServiceTest.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTestLocal.mwmWebServiceTest.HelloWorldResponse WebServiceTestLocal.mwmWebServiceTest.WebService1Soap.HelloWorld(WebServiceTestLocal.mwmWebServiceTest.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServiceTestLocal.mwmWebServiceTest.HelloWorldRequest inValue = new WebServiceTestLocal.mwmWebServiceTest.HelloWorldRequest();
            inValue.Body = new WebServiceTestLocal.mwmWebServiceTest.HelloWorldRequestBody();
            WebServiceTestLocal.mwmWebServiceTest.HelloWorldResponse retVal = ((WebServiceTestLocal.mwmWebServiceTest.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceTestLocal.mwmWebServiceTest.HelloWorldResponse> WebServiceTestLocal.mwmWebServiceTest.WebService1Soap.HelloWorldAsync(WebServiceTestLocal.mwmWebServiceTest.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceTestLocal.mwmWebServiceTest.HelloWorldResponse> HelloWorldAsync() {
            WebServiceTestLocal.mwmWebServiceTest.HelloWorldRequest inValue = new WebServiceTestLocal.mwmWebServiceTest.HelloWorldRequest();
            inValue.Body = new WebServiceTestLocal.mwmWebServiceTest.HelloWorldRequestBody();
            return ((WebServiceTestLocal.mwmWebServiceTest.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTestLocal.mwmWebServiceTest.GetStrResponse WebServiceTestLocal.mwmWebServiceTest.WebService1Soap.GetStr(WebServiceTestLocal.mwmWebServiceTest.GetStrRequest request) {
            return base.Channel.GetStr(request);
        }
        
        public string GetStr(string name) {
            WebServiceTestLocal.mwmWebServiceTest.GetStrRequest inValue = new WebServiceTestLocal.mwmWebServiceTest.GetStrRequest();
            inValue.Body = new WebServiceTestLocal.mwmWebServiceTest.GetStrRequestBody();
            inValue.Body.name = name;
            WebServiceTestLocal.mwmWebServiceTest.GetStrResponse retVal = ((WebServiceTestLocal.mwmWebServiceTest.WebService1Soap)(this)).GetStr(inValue);
            return retVal.Body.GetStrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceTestLocal.mwmWebServiceTest.GetStrResponse> WebServiceTestLocal.mwmWebServiceTest.WebService1Soap.GetStrAsync(WebServiceTestLocal.mwmWebServiceTest.GetStrRequest request) {
            return base.Channel.GetStrAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceTestLocal.mwmWebServiceTest.GetStrResponse> GetStrAsync(string name) {
            WebServiceTestLocal.mwmWebServiceTest.GetStrRequest inValue = new WebServiceTestLocal.mwmWebServiceTest.GetStrRequest();
            inValue.Body = new WebServiceTestLocal.mwmWebServiceTest.GetStrRequestBody();
            inValue.Body.name = name;
            return ((WebServiceTestLocal.mwmWebServiceTest.WebService1Soap)(this)).GetStrAsync(inValue);
        }
    }
}
