//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mainEntities : DbContext
    {
        public mainEntities()
            : base("name=mainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<t_FIA8K_Channel> t_FIA8K_Channel { get; set; }
        public DbSet<t_FIA8K_ChannelParam> t_FIA8K_ChannelParam { get; set; }
        public DbSet<t_FIA8K_ChannelTestPara> t_FIA8K_ChannelTestPara { get; set; }
        public DbSet<t_FIA8K_Data> t_FIA8K_Data { get; set; }
        public DbSet<t_FIA8K_Device> t_FIA8K_Device { get; set; }
        public DbSet<t_FIA8K_DevicePart> t_FIA8K_DevicePart { get; set; }
        public DbSet<t_FIA8K_Dilutor> t_FIA8K_Dilutor { get; set; }
        public DbSet<t_FIA8K_DilutorParam> t_FIA8K_DilutorParam { get; set; }
        public DbSet<t_FIA8K_Function> t_FIA8K_Function { get; set; }
        public DbSet<t_FIA8K_History> t_FIA8K_History { get; set; }
        public DbSet<t_FIA8K_Injector> t_FIA8K_Injector { get; set; }
        public DbSet<t_FIA8K_InjectorParam> t_FIA8K_InjectorParam { get; set; }
        public DbSet<t_FIA8K_InjectorTestPara> t_FIA8K_InjectorTestPara { get; set; }
        public DbSet<t_FIA8K_Log> t_FIA8K_Log { get; set; }
        public DbSet<t_FIA8K_Method> t_FIA8K_Method { get; set; }
        public DbSet<t_FIA8K_MethodParam> t_FIA8K_MethodParam { get; set; }
        public DbSet<t_FIA8K_Part> t_FIA8K_Part { get; set; }
        public DbSet<t_FIA8K_Project> t_FIA8K_Project { get; set; }
        public DbSet<t_FIA8K_PumpSpeedGradient> t_FIA8K_PumpSpeedGradient { get; set; }
        public DbSet<t_FIA8K_ReportInfo> t_FIA8K_ReportInfo { get; set; }
        public DbSet<t_FIA8K_Role> t_FIA8K_Role { get; set; }
        public DbSet<t_FIA8K_RolePerm> t_FIA8K_RolePerm { get; set; }
        public DbSet<t_FIA8K_Sample> t_FIA8K_Sample { get; set; }
        public DbSet<t_FIA8K_SamplePeak> t_FIA8K_SamplePeak { get; set; }
        public DbSet<t_FIA8K_Test> t_FIA8K_Test { get; set; }
        public DbSet<t_FIA8K_TestConfigPara> t_FIA8K_TestConfigPara { get; set; }
        public DbSet<t_FIA8K_TestSample> t_FIA8K_TestSample { get; set; }
        public DbSet<t_FIA8K_User> t_FIA8K_User { get; set; }
        public DbSet<t_FIA8K_UserRole> t_FIA8K_UserRole { get; set; }
        public DbSet<t_FIA8K_Warning> t_FIA8K_Warning { get; set; }
        public DbSet<t_FIA8K_WorkLine> t_FIA8K_WorkLine { get; set; }
        public DbSet<t_FIA8K_WorkLinePoint> t_FIA8K_WorkLinePoint { get; set; }
    }
}
