//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_FIA8K_Project
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<System.DateTime> TESTTIME { get; set; }
        public string TESTER { get; set; }
        public Nullable<long> DEVICEID { get; set; }
        public string CHANNELCODE { get; set; }
        public string MAINCHANNELCODE { get; set; }
        public string INJECTORCODE { get; set; }
        public string CONFIGFILEPATH { get; set; }
        public string METHODFILEPATH { get; set; }
        public string SEQUENCEFILEPATH { get; set; }
        public string WORKLINEFILEPATH { get; set; }
        public string RESULTFILEPATH { get; set; }
        public string REPORTFILEPATH { get; set; }
        public string REMARK { get; set; }
        public string INSERTUSER { get; set; }
        public Nullable<System.DateTime> INSERTDATETIME { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATETIME { get; set; }
    }
}
