//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_FIA8K_ChannelParam
    {
        public long ID { get; set; }
        public Nullable<int> WAVELENGTH { get; set; }
        public Nullable<double> PEAKTIME { get; set; }
        public Nullable<int> HEATING1 { get; set; }
        public Nullable<int> HEATING2 { get; set; }
        public Nullable<int> CONDENSINGUNIT { get; set; }
        public Nullable<int> ULTRADIGESIONUNIT { get; set; }
        public Nullable<int> ROTARVALVE1POSITION { get; set; }
        public Nullable<int> ROTARVALVE2POSITION { get; set; }
        public Nullable<int> LAMPSTATE { get; set; }
        public Nullable<int> LIGHTINTENSITY { get; set; }
        public Nullable<int> DISTRIBUTINGVALVEPOSITION { get; set; }
        public Nullable<double> INTEGRALWIDTH { get; set; }
        public Nullable<int> INTEGRALAREASTARTTIME { get; set; }
        public Nullable<int> INTEGRALAREAWIDTH { get; set; }
        public Nullable<int> PUMPSPEEDGRADIENT { get; set; }
        public Nullable<int> PUMPSPEED { get; set; }
        public Nullable<int> ARRIVALTIME { get; set; }
        public Nullable<int> INJECTTIME { get; set; }
        public Nullable<int> CYCLETIME { get; set; }
        public Nullable<int> SPEEDGRADIENTSTARTTIME { get; set; }
        public Nullable<int> PICKMODE { get; set; }
        public Nullable<int> FADINGREATION { get; set; }
        public string WAVELENGTHVALUES { get; set; }
        public Nullable<int> DLDELAY { get; set; }
        public string REMARK { get; set; }
        public string INSERTUSER { get; set; }
        public Nullable<System.DateTime> INSERTDATETIME { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATETIME { get; set; }
    }
}
