//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_FIA8K_Test
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> TESTTIME { get; set; }
        public string TESTER { get; set; }
        public string DEVICEID { get; set; }
        public Nullable<int> DEVICETYPE { get; set; }
        public string METHODID { get; set; }
        public Nullable<int> PICKMODE { get; set; }
        public Nullable<int> DECIMALDIGITS { get; set; }
        public Nullable<int> FITTINGTIMES { get; set; }
        public Nullable<int> PICKFREQUENCY { get; set; }
        public string REMARK { get; set; }
        public string INSERTUSER { get; set; }
        public Nullable<System.DateTime> INSERTDATETIME { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATETIME { get; set; }
    }
}
