//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_FIA8K_Role
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> STATE { get; set; }
        public string INSERTUSER { get; set; }
        public Nullable<System.DateTime> INSERTDATETIME { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATETIME { get; set; }
    }
}
